Fixed Issue #123
Koukyosyumei/AIJack pull request #178
Opened 2024-04-14 05:29 UTC by theperiperi

changed type() to isinstance() for typechecks in  [src/aijack/defense/paillier/torch_wrapper.py](https://github.com/Koukyosyumei/AIJack/blob/316fcc0c3bbfcd2eaabbf18acf3d27f43b505f70/src/aijack/defense/paillier/torch_wrapper.py)

2024-04-14 06:02 UTC, Koukyosyumei commented
@theperiperi Hi! Thanks for your excellent suggestions! Please check my comments.

2024-04-15 06:48 UTC, theperiperi commented
I don't see any comments, where do I check them?

2024-04-15 06:52 UTC, Koukyosyumei requested changes

2024-04-15 06:53 UTC, Koukyosyumei commented
I'm sorry I forgot to making my comments public. I think now you can see my comments.

2024-04-15 08:29 UTC, theperiperi commented on src/aijack/defense/paillier/torch_wrapper.py
> +        if isinstance(paillier_array) == list:
yes,fixed it

2024-04-15 09:39 UTC, Koukyosyumei requested changes
Please check the document of isinstance. https://docs.python.org/3/library/functions.html#isinstance

2024-04-15 11:31 UTC, Koukyosyumei approved these changes

2024-04-15 11:32 UTC, merged